import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';

// Inline the branded welcome page (host/welcome.html) as a string constant so the
// packaged single-file exe can write + open it on self-install (no sidecar file to
// ship). Generated into src/ before bundling — gitignored, regenerated every build.
const welcome = readFileSync(new URL('./host/welcome.html', import.meta.url), 'utf8');
writeFileSync(
  new URL('./src/welcome-html.ts', import.meta.url),
  `// Generated by build.mjs from host/welcome.html — do not edit by hand.\nexport const WELCOME_HTML = ${JSON.stringify(welcome)};\n`
);

// Self-contained CJS files — zero deps, so `node dist/*.cjs` needs no resolution
// context. .cjs because the package is "type": "module". Two bins: the CLI
// (origami-serve) and the native-messaging host (Origami Live's one-click Go Live).
const common = {
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node20',
  banner: { js: '#!/usr/bin/env node' },
  logLevel: 'warning',
};
await build({ ...common, entryPoints: ['src/cli.ts'], outfile: 'dist/cli.cjs' });
await build({ ...common, entryPoints: ['src/host.ts'], outfile: 'dist/host.cjs' });
console.log('origami-serve built -> dist/cli.cjs, dist/host.cjs');
